In [1]:
import mediapipe as mp
import cv2
import uuid
import os
import numpy as np

In [2]:
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

In [3]:
os.path.exists("Gestures\Gesture_1\gesture.csv")

False

In [7]:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(min_detection_confidence=0.8 , min_tracking_confidence = 0.5) as hands:
    count = 0
    while cap.isOpened() and count!= 1000:
        res , frame = cap.read()
        
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        results = hands.process(image)
        image.flags.writeable = True
        image = cv2.cvtColor(image , cv2.COLOR_RGB2BGR)
        

        
        if results.multi_hand_landmarks:
                
                cv2.imwrite(os.path.join(f"Gestures\Gesture_2\Gesture_2","{}.jpg".format(f'image_{count}')),frame)
                count+=1
                            
#                 if count%1000:
#                     i+=1        
#                 cv2.imwrite(os.path.join(f"Gestures\Gesture_{i}","{}.jpg".format(uuid.uuid1())),xtr)
                
            
#         if results.multi_hand_landmarks:
#             xtr = np.array([a[0].landmark[i].x for i in range(21)] +
#                [a[0].landmark[i].y for i in range(21)] +
#                [a[0].landmark[i].z for i in range(21)])

#             xtr = xtr.flatten()  # Flatten the array to create a 1D array if needed

#             gesture = model.predict(xtr)
#             if gesture in Gestures:
#                 #perform action based on gesture
            
        
        cv2.imshow("Hand Tracking ",image)

        if cv2.waitKey(10) & 0xff == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

In [5]:
print(frame)

[[[ 94  74  75]
  [ 96  75  76]
  [ 99  77  78]
  ...
  [170 143 146]
  [172 146 147]
  [175 148 149]]

 [[ 97  77  79]
  [ 97  76  78]
  [ 98  76  78]
  ...
  [169 141 147]
  [172 145 149]
  [173 146 150]]

 [[ 98  79  83]
  [ 97  77  81]
  [ 95  75  79]
  ...
  [163 135 144]
  [170 142 150]
  [172 144 152]]

 ...

 [[167 152 126]
  [167 152 128]
  [169 154 131]
  ...
  [ 80  63  84]
  [ 81  64  85]
  [ 84  67  87]]

 [[174 157 129]
  [171 155 128]
  [172 157 132]
  ...
  [ 80  63  85]
  [ 80  63  84]
  [ 83  65  86]]

 [[182 164 135]
  [183 166 139]
  [176 160 135]
  ...
  [ 84  66  88]
  [ 84  67  87]
  [ 85  68  89]]]


In [6]:
results.multi_hand_landmarks